packaging_format = 2

id = "fittrackee"
name = "FitTrackee"
description.en = "Self-hosted outdoor activity tracker 🚴"
description.gl = "Rexistra as túas actividades ao aire libre 🚴"
description.ca = "Seguiment d'activitats a l'aire lliure autoallotjat 🚴"
description.fr = "Traqueur d’activités extérieures auto-hébergé 🚴"

version = "0.9.0b3~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0-only"
website = "https://samr1.github.io/FitTrackee"
demo = ""
admindoc = "https://samr1.github.io/FitTrackee"
code = "https://github.com/SamR1/FitTrackee"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"
    help.en = "You will have to login with the email of this user and the password you’ll set below."
    help.fr = "Vous devrez vous connecter avec l’adresse courriel de cet utilisateur et le mot de passe configuré ci-dessous."

    [install.password]
    help.en = "Choose a password for your admin user here."
    help.gl = "Elixe un contrasinal para a usuaria Admin en FitTrackee."
    help.ca = "Triar una contrasenya per a l'usuari d'administració."
    help.fr = "Choisissez un mot de passe pour l’utilisateur admin ici."
    type = "password"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    # choices can be retrieved in fittrackee/config.py SUPPORTED_LANGUAGES
    choices = ["cs", "de", "en", "es", "eu", "fr", "gl", "it", "nb", "nl", "pl", "pt"]
    default = "en"

    [install.weather_api_provider]
    ask.en = "(Optional) Choose your weather provider between Darksky and Visual Crossing"
    ask.gl = "(Optativo) Elixe o provedor de meteoroloxía, entre Darksky e Visual Crossing"
    ask.ca = "(Opcional) Escollir un proveïdor del temps entre Darksky i Visual Crossing"
    ask.fr = "(Optionnel) Choisissez votre fournisseur météo entre Darksky et Visual Crossing"
    help.en = "Since Fittrackee 0.7.15, only Visual Crossing is supported"
    help.gl = "Desde Fittrackee 0.7.15, só temos soporte para Visual Crossing"
    help.ca = "Des de Fittrackee 0.7.15, només es suporta l'ús de Visual Crossing"
    help.fr = "Depuis Fittrackee 0.7.15, seul Visual Crossing est supporté"
    type = "select"
    choices = ["", "visualcrossing"]
    default = "visualcrossing"
    optional = true

    [install.weather_api_key]
    ask.en = "(Optional) Insert here the api key from the chosen weather provider"
    ask.gl = "(Optativo) Escribe aquí a chave da API do provedor de meteoroloxía elexido"
    ask.ca = "(Opcional) Inserir la clau de l'API del proveïdor del temps escollit"
    ask.fr = "(Optionnel) Insérez ici la clé API du fournisseur de météo choisi"
    type = "string"
    default = false
    optional = true

  [resources]
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3, python3-venv, libopenjp2-7, redis-server"

    [resources.database]
    type = "postgresql"
