packaging_format = 2

id = "fittrackee"
name = "FitTrackee"
description.en = "Self-hosted outdoor activity tracker 🚴"
description.fr = "Traqueur d’activités extérieures auto-hébergé 🚴"

version = "0.7.25~ynh3"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://samr1.github.io/FitTrackee"
demo = ""
admindoc = "https://samr1.github.io/FitTrackee"
code = "https://github.com/SamR1/FitTrackee"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
      
    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    help.en = "Choose a password for your admin user here."
    help.fr = "Choisissez un mot de passe pour l’utilisateur admin ici."
    type = "password"

    [install.weather_provider]
    ask.en = "(Optional) Choose your weather provider between Darksky and Visual Crossing"
    ask.fr = "(Optionnel) Choisissez votre fournisseur météo entre Darksky et Visual Crossing"
    help.en = "Since Fittrackee 0.7.15, only Visual Crossing is supported"
    help.fr = "Depuis Fittrackee 0.7.15, seul Visual Crossing est supporté"
    type = "select"
    choices = ["", "visualcrossing"]
    default = "visualcrossing"
    optional = true

    [install.weather_key]
    ask.en = "(Optional) Insert here the api key from the chosen weather provider"
    ask.fr = "(Optionnel) Insérez ici la clé API du fournisseur de météo choisi"
    type = "string"
    default = false
    optional = true

  [resources]
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    
    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3, python3-venv, libopenjp2-7"

    [resources.database]
    type = "postgresql"
