test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    
    test_upgrade_from.d682f12.name = "0.7.25~ynh3"
    test_upgrade_from.e48197d.name = "0.7.26"
    test_upgrade_from.33f7a78.name = "0.7.27"
    test_upgrade_from.ac79c26.name = "0.7.28"