test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    test_upgrade_from.9fde2b0.name = "0.8.12"

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from

    # -------------------------------
    test_upgrade_from.ab2325a.name = "0.8.12"
    test_upgrade_from.9171a7e.name = "0.8.13"
    test_upgrade_from.d5f6343.name = "0.9.0"
