test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    test_upgrade_from.499f21b.name = "0.7.32"
    test_upgrade_from.5b6ccd1.name = "0.8.0"
    test_upgrade_from.6c23ccf.name = "0.8.1"
    test_upgrade_from.2c6b69d.name = "0.8.3"
    test_upgrade_from.fb74b14.name = "0.8.4"
   