test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    test_upgrade_from.853024c.name = "helpers_v1 + 0.8.5"
    test_upgrade_from.ec414ce.name = "0.8.6"
    test_upgrade_from.064f8a4.name = "0.8.7"
    test_upgrade_from.115ab41.name = "0.8.8"
    test_upgrade_from.512bd58.name = "0.8.9~ynh1"
    test_upgrade_from.bd4f977.name = "0.8.9~ynh2"