test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    
     exclude = ["change_url", "install.weather_provider", "install.weather_key"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
   
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

