test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
    
    test_upgrade_from.ca02214.name = "0.7.18"
    test_upgrade_from.9c094f9.name = "0.7.21"
    test_upgrade_from.e49294c.name = "0.7.22"
