test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    test_upgrade_from.9fde2b0.name = "0.8.12"

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------