#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop" --service="${app}"

ynh_systemctl --action="stop" --service="${app}_workers"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY THE CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

domain=$new_domain
ynh_config_add --template=".env.production" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting the systemd services..."

ynh_systemctl --service="${app}" --action="start"

ynh_systemctl --service="${app}_workers" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"