#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================


#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__heatmap_base_zoom() {
    ynh_app_setting_set --key=heatmap_base_zoom --value=$heatmap_base_zoom
    ynh_config_add --template=".env" --destination="$install_dir/.env"

    set -a
    source $install_dir/.env
    ynh_hide_warnings $install_dir/venv/bin/ftcli workouts rebuild_heatmap
    set +a
}

#=================================================
ynh_app_config_run $1
