#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_config_remove_fail2ban

ynh_config_remove_logrotate

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi
if ynh_hide_warnings yunohost service status ${app}-workers >/dev/null; then
	yunohost service remove ${app}-workers
fi

ynh_config_remove_systemd "${app}"
ynh_config_remove_systemd "${app}-workers"

ynh_config_remove_nginx

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
