#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

redis_db=$(ynh_app_setting_get --key=redis_db)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
	yunohost service remove ${app}_workers
fi

ynh_config_remove_systemd "${app}"
ynh_config_remove_systemd "${app}_workers"

ynh_config_remove_nginx

ynh_config_remove_logrotate

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
