#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop" --service="${app}"
ynh_systemctl --action="stop" --service="${app}_workers"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=redis_db --value=$(ynh_redis_get_free_db)
ynh_app_setting_set_default --key=weather_provider --value=$weather_api_provider
ynh_app_setting_set_default --key=weather_key --value=$weather_api_key

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env.production" --destination="$install_dir/.env"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

if [ $YNH_ARCH == "armhf" ] || [ $YNH_ARCH == "armel" ]
then
# Install rustup if not already installed
# We need this to be able to install cryptgraphy on ARM hardware
export PATH="$PATH:$install_dir/.cargo/bin:$install_dir/.local/bin:/usr/local/sbin"
    if [ -e $install_dir/.rustup ]; then
    ynh_exec_as_app PATH=$PATH rustup update
    else
    ynh_exec_as_app bash -c 'curl -sSf -L https://static.rust-lang.org/rustup.sh | sh -s -- -y --default-toolchain=stable --profile=minimal'
    fi
fi

pushd "$install_dir"
    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade wheel toml pyyaml
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install fittrackee=="$(ynh_app_upstream_version)"

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#Logrotate has to be added now, because the app won’t start if there are no logs files
ynh_config_add_logrotate

#=================================================
# Update DATABASE
#=================================================
ynh_script_progression "Upgrading database..."

set -a

source $install_dir/.env

ynh_hide_warnings $install_dir/venv/bin/ftcli db upgrade

if ynh_app_upgrading_from_version_before 0.9.0~ynh1
then
   ynh_hide_warnings $install_dir/venv/bin/ftcli users update $admin --set-role owner
fi

set +a

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}"   --template="fittrackee.service"
ynh_config_add_systemd --service="${app}_workers" --template="fittrackee_workers.service"

yunohost service add "${app}" --description="Fittrackee main service" --log="/var/log/$app/$app.log"
yunohost service add "${app}_workers" --description="Fittrackee task queue service" --log="/var/log/$app/${app}_workers.log"

#ynh_hide_warnings has to be set for the Bookworm version of fail2ban, further OS realease have this bug resoled (normally)
ynh_hide_warnings ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-access.log" --failregex="<HOST>.* \"POST /api/auth/login HTTP/\d.\d\" 40"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="${app}" --action="start"
ynh_systemctl --service="${app}_workers" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
